-- don't forget install clang-format
-- :ConformInfo to check
return {
    -- {
    --     "stevearc/conform.nvim",
    --     opts = {
    --         log_level = vim.log.levels.DEBUG,
    --         formatters = {
    --             -- xmlformat = {
    --             -- prepend_args = { "--preserve 'literal'", "--eof-newline", "--selfclose", "--blanks" },
    --             -- command = "xmlformat",
    --             -- },
    --         },
    --         formatters_by_ft = {
    --             c = { "clang_format" },
    --             h = { "clang_format" },
    --             cpp = { "clang_format" },
    --             hpp = { "clang_format" },
    --             cuda = { "clang_format" },
    --             -- xslt = { "mytidy" },
    --             -- xml = { "mytidy" },
    --             -- xsl = { "mytidy" },
    --             -- ant = { "mytidy" },
    --             -- typst = { "typstfmt" },
    --             -- xslt = { "xmlformat" },
    --             -- xml = { "xmlformat" },
    --             -- xsl = { "xmlformat" },
    --             -- ant = { "xmlformat" },
    --         },
    --         lsp_fallback = true,
    --     },
    -- },
}
