return {
    -- {
    --     "SylvanFranklin/omni-preview.nvim",
    --     opts = {},
    --     lazy = true,
    --     keys = {
    --         {
    --             "<leader>cp",
    --             "<cmd>OmniPreview toggle<cr>",
    --             mode = { "n", "x" },
    --             desc = "OmniPreview",
    --         },
    --     },
    --     ft = { "typst", "csv", "latex", "tex" },
    --     dependencies = {
    --         -- Typst
    --         { "toppair/peek.nvim", lazy = true },
    --         { "chomosuke/typst-preview.nvim", lazy = true },
    --         -- CSV
    --         { "hat0uma/csvview.nvim", lazy = true },
    --     },
    -- },
}
